// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

// <auto-generated>
// Exclude this file from StyleCop analysis. This file is generated and may be added to projects.
// DO NOT MODIFY. Changes to this file may cause incorrect behavior and will be lost on updates.
// </auto-generated>

namespace Microsoft.WindowsAppSDK
{
    // Release information
    public class Release
    {
        /// The major version of the Windows App SDK release.
        public const ushort Major = 1;

        /// The minor version of the Windows App SDK release.
        public const ushort Minor = 3;

        /// The patch version of the Windows App SDK release.
        public const ushort Patch = 0;

        /// The major and minor version of the Windows App SDK release, encoded as a uint32_t (0xMMMMNNNN where M=major, N=minor).
        public const uint MajorMinor = 0x00010003;

        /// The Windows App SDK release's channel; for example, "preview", or empty string for stable.
        public const string Channel = "preview";

        /// The Windows App SDK release's version tag; for example, "preview2", or empty string for stable.
        public const string VersionTag = "preview1";

        /// The Windows App SDK release's short-form version tag; for example, "p2", or empty string for stable.
        public const string VersionShortTag = "p1";

        /// The Windows App SDK release's version tag, formatted for concatenation when constructing identifiers; for example, "-preview2", or empty string for stable.
        public const string FormattedVersionTag = "-preview1";

        /// The Windows App SDK release's short-form version tag, formatted for concatenation when constructing identifiers; for example, "-p2", or empty string for stable.
        public const string FormattedVersionShortTag = "-p1";
    }

    // Runtime information
    namespace Runtime
    {
        public class Identity
        {
            /// The Windows App SDK runtime's package identity's Publisher.
            public const string Publisher = "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US";

            /// The Windows App SDK runtime's package identity's PublisherId.
            public const string PublisherId = "8wekyb3d8bbwe";
        }

        public class Version
        {
            /// The major version of the Windows App SDK runtime; for example, 1000.
            public const ushort Major = 3000;

            /// The minor version of the Windows App SDK runtime; for example, 446.
            public const ushort Minor = 788;

            /// The build version of the Windows App SDK runtime; for example, 804.
            public const ushort Build = 1817;

            /// The revision version of the Windows App SDK runtime; for example, 0.
            public const ushort Revision = 0;

            /// The version of the Windows App SDK runtime, as a uint64l for example, 0x03E801BE03240000.
            public const ulong UInt64 = 0x0BB8031407190000;

            /// The version of the Windows App SDK runtime, as a string (const wchar_t*); for example, "1000.446.804.0".
            public const string DotQuadString = "3000.788.1817.0";
        }

        namespace Packages
        {
            public class Framework
            {
                /// The Windows App SDK runtime's Framework package's family name.
                public const string PackageFamilyName = "Microsoft.WindowsAppRuntime.1.3-preview1_8wekyb3d8bbwe";
            }
            public class Main
            {
                /// The Windows App SDK runtime's Main package's family name.
                public const string PackageFamilyName = "MicrosoftCorporationII.WinAppRuntime.Main.1.3-p1_8wekyb3d8bbwe";
            }
            public class Singleton
            {
                /// The Windows App SDK runtime's Singleton package's family name.
                public const string PackageFamilyName = "MicrosoftCorporationII.WinAppRuntime.Singleton-p1_8wekyb3d8bbwe";
            }
            namespace DDLM
            {
                public class X86
                {
                    /// The Windows App SDK runtime's Dynamic Dependency Lifetime Manager (DDLM) package's family name, for x86.
                    public const string PackageFamilyName = "Microsoft.WinAppRuntime.DDLM.3000.788.1817.0-x8-p1_8wekyb3d8bbwe";
                }
                public class X64
                {
                    /// The Windows App SDK runtime's Dynamic Dependency Lifetime Manager (DDLM) package's family name, for x64.
                    public const string PackageFamilyName = "Microsoft.WinAppRuntime.DDLM.3000.788.1817.0-x6-p1_8wekyb3d8bbwe";
                }
                public class Arm64
                {
                    /// The Windows App SDK runtime's Dynamic Dependency Lifetime Manager (DDLM) package's family name, for arm64.
                    public const string PackageFamilyName = "Microsoft.WinAppRuntime.DDLM.3000.788.1817.0-a6-p1_8wekyb3d8bbwe";
                }
            }
        }
    }
}
